[package]
name = "multicodec"
version = "0.2.5"
edition = "2021"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>", "Dave Huseby <dwh@linuxprogrammer.org>"]
description = "implementing the multicodec spec"
repository = "https://github.com/cryptidtech/rust-multicodec"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["multiformats", "multicodec", "serde"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
unsigned-varint = { version = "0.7", features = ["std"] }

[build-dependencies]
convert_case = "0.6"
csv = "1.3"
serde = "1.0"
serde_derive = "1.0"
