[package]
name = "multi-codec"
version = "1.5.0"
edition = "2024"
rust-version = "1.85"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>", "Dave Grantham <dwg@linuxprogrammer.org>"]
description = "Implementation of the Multicodec specification"
repository = "https://github.com/cryptidtech/multi-codec.git"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["multiformats", "multicodec", "serde", "no_std"]
categories = ["encoding"]

[features]
default = ["std", "serde"]
std = ["thiserror/std", "serde/std", "multi-trait/std"]
serde = ["dep:serde"]

[dependencies]
multi-trait = { version = "1.0", default-features = false }
thiserror = { version = "2.0", default-features = false }
serde = { version = "1.0", default-features = false, optional = true, features = ["serde_derive"] }

[dev-dependencies]
ciborium = "0.2"
criterion = { version = "0.8", features = ["html_reports"] }
hex = "0.4"
proptest = "1.4"
serde_json = "1.0"
serde_test = "1.0"
unsigned-varint = { version = "0.8", features = ["std"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

[lints.rust]
unsafe_code = "deny"

[[bench]]
name = "codec_bench"
harness = false
path = "benches/codec_bench.rs"

[[example]]
name = "uvi"
path = "examples/uvi.rs"

[build-dependencies]
convert_case = "0.12"
csv = "1.3"
serde = { version = "1.0", features = ["serde_derive"] }
serde_derive = "1.0"
